### ISSUE TITLE
Possibilities to follow redirect?

### ISSUE THREAD

**Issue by ThomasG77** [marcograss/partialzip#3]
I've tried an URL like https://data.economie.gouv.fr/api/datasets/1.0/documents-de-filiation-informatises-dfi-des-parcelles/attachments/documents_de_filiations_informatises_situation_juillet_2022_dept_600_a_dept_976_zip

Because it's a redirection, partialzip does not detect it's a zip (not obvious as there is no extension), hence it does "not work" in this case (`partialzip list https://data.economie.gouv.fr/api/datasets/1.0/documents-de-filiation-informatises-dfi-des-parcelles/attachments/documents_de_filiations_informatises_situation_juillet_2022_dept_600_a_dept_976_zip`) because it's an unsupported behaviour.

If you try `curl --head https://data.economie.gouv.fr/api/datasets/1.0/documents-de-filiation-informatises-dfi-des-parcelles/attachments/documents_de_filiations_informatises_situation_juillet_2022_dept_600_a_dept_976_zip`, you are able to find out the returned file is a `content-type: application/zip`

The idea on the paper would be to implement when no extension, do a http head request to check if mimetype/content-type is zip and then deal with it like usual following redirection if necessary.

**Comment by marcograss** [comment]
thanks, this is a good idea, I will look into it and I will push it in the next release

**Comment by marcograss** [comment]
after some investigation, it seems this server don't support the Range headers, so it's not possible to partially read the file, I don't think in this case the redirect is the issue but I will continue to look into it

**Comment by ThomasG77** [comment]
If not possible due to remote server capabilities, don't try to much and we will close the issue.

**Comment by SilverBut** [comment]
Actually the URL mentioned above is not a redirection:
```
curl -I https://data.economie.gouv.fr/api/datasets/1.0/documents-de-filiation-informatises-dfi-des-parcelles/attachments/documents_de_filiations_informatises_situation_juillet_2022_dept_600_a_dept_976_zip
HTTP/2 200 
server: nginx
date: Wed, 26 Oct 2022 19:26:57 GMT
content-type: application/zip
content-length: 148916817
```

And current code can process redirection well, which can be reproduced by add `easy.verbose(true)?;`, and check the log:
```
➜ cargo run list http://example.localhost
    Finished dev [unoptimized + debuginfo] target(s) in 0.40s
     Running `target/debug/partialzip list 'http://example.localhost'
//...
> HEAD / HTTP/1.1
Host: example.localhost
Accept: */*

* Mark bundle as not supporting multiuse
< HTTP/1.1 302 Moved Temporarily
< Location: http://example.localhost/a.zip
< 
//...
> HEAD /a.zip HTTP/1.1
Host: example.localhost
Accept: */*
```

**Comment by ThomasG77** [comment]
So, I think I can close. Reopen if you feel it's necessary
