### ISSUE TITLE
Support HTTP gzip compression

### ISSUE THREAD

**Issue by JJTech0130** [marcograss/partialzip#4]
Certain web servers (looking at you `apps.mzstatic.com`) only support the `Range` header when using GZIP compression. Would be cool to have a flag to enable it. Would also reduce bandwidth for normal servers.

**Comment by JJTech0130** [comment]
I read into this a bit more, and it seems like it isn't actually possible as the gzip encoding is for the whole thing, and you are taking a range of the gzipped data. As gzip can't be partially decompressed except from the beginning (without an index file), this wouldn't work.

**Comment by marcograss** [comment]
unfortunately yes, gzip is a single file container
